---

namespace: 'oxlorg'
name: 'systemd'
version: 1.0.2
readme: 'README.md'
authors:
  - 'OXL IT Services <contact+systemd@oxl.at>'
description: "Ansible modules to work with systemd (journalctl)"
license_file: 'LICENSE.txt'
tags:
  - 'systemd'
  - 'journal'
  - 'journalctl'
  - 'logs'
  - 'logging'
dependencies: {}
repository: 'https://github.com/O-X-L/ansible-collection-systemd'
documentation: 'https://ansible-systemd.oxl.app'
homepage: 'https://www.OXL.at'
issues: 'https://github.com/O-X-L/ansible-collection-systemd/issues'
build_ignore: [
  '*_pytest.py', '*_testdata.py', '*pytest_cache', '*/_tmpl.py',
  '.**', 'pytest.ini', 'requirements_*.txt',
  'docs**', 'scripts**', 'venv**', 'Makefile', 'legacy**',
]
