---

name: Lint

on:
  push:
    branches: [latest]
    paths:
      - '**.py'
      - '**.yml'
      - '.github/workflows/test.yml'
      - 'requirements_lint.txt'
  pull_request:
    branches: [latest]
    paths:
      - '**.py'
      - '**.yml'
      - '.github/workflows/test.yml'
      - 'requirements_lint.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements_lint.txt
        shell: bash

      - name: Running PyLint
        run: pylint --recursive=y .
        shell: bash

      - name: Running YamlLint
        run: yamllint .
        shell: bash
